---
- hosts: linux
  become: yes
  become_user: root
  roles:
     - ansible-role-java

#  tasks:
#    - name: test connection
#      ping:


#- hosts: windows
#  remote_user: davemus
#  tasks:
#    - name: test connection
#      win_ping:
#

